[package]
name = "feh-sim-seed"
version = "0.1.0"
authors = ["Minno"]
edition = "2018"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.37"
num_enum = "0.1.1"
lazy_static = "1.2.0"

[dependencies.web-sys]
version = "0.3.14"
features = ["Performance"]

[dependencies.rand]
version = "0.6.5"
default-features = false
features = ["wasm-bindgen", "std"]

[dependencies.nom]
version = "4.2.0"
default-features = false

[profile.release]
lto = true
panic = "abort"